version: 2

builds:
  - env:
      - CGO_ENABLED=0

homebrew_casks:
  - repository:
      owner: hoffa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/hoffa/vitree
    description: Vim file browser running in a separate terminal
    custom_block: |
      postflight_steps do
        on_macos do
          run "/usr/bin/xattr",
              args:  ["-dr", "com.apple.quarantine", "{{ .ProjectName }}"],
              chdir: "."
        end
      end
