version: 2

builds:
  - env:
      - CGO_ENABLED=0

homebrew_casks:
  - repository:
      owner: hoffa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/hoffa/vitree
    description: A Vim file browser running in a separate terminal
    url:
      verified: github.com/hoffa/vitree
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vitree"]
          end
