version: 2

builds:
  - env:
      - CGO_ENABLED=0

brews:
  - repository:
      owner: hoffa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/hoffa/vitree
    description: Tiny Go TUI that browses the current directory and forwards files to vim
    license: MIT
    test: |
      system "#{bin}/vitree", "-version"
